export class ActionNames {

	static HN_GET_ITEM = "HN_GET_ITEM";
	static HN_GET_CHILD_ITEMS = "HN_GET_CHILD_ITEMS";
	static HN_GET_ITEM_COMPLETED = "HN_GET_ITEM_COMPLETED";
	static HN_GET_CHILD_ITEM_COMPLETED = "HN_GET_CHILD_ITEM_COMPLETED";
}